<a href="https://colab.research.google.com/github/Obulreddy0/pandas_practise/blob/main/pandas_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
s=pd.Series([10,20,30],index=["alice","bob","char"])
print(s)

alice    10
bob      20
char     30
dtype: int64

In [ ]:
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [28, 35, 22],
    "city": ["Mumbai", "Delhi", "Pune"]
})
print(df)

      name  age    city
0    Alice   28  Mumbai
1      Bob   35   Delhi
2  Charlie   22    Pune

In [ ]:
# Accessing a column from a DataFrame returns a Series
print(type(df["name"]))  # <class 'pandas.core.series.Series'>

<class 'pandas.core.series.Series'>

In [ ]:
# Create a Series of 5 fruits: "Apple", "Banana", "Mango", "Grapes", "Orange" with default index.
fruits = pd.Series(["Apple", "Banana", "Mango", "Grapes", "Orange"])
print(fruits)

0     Apple
1    Banana
2     Mango
3    Grapes
4    Orange
dtype: object

In [ ]:
#  Create a Series of prices [120, 40, 80, 60, 50] with the fruit names as the index.
prices = pd.Series([120, 40, 80, 60, 50], index=["Apple", "Banana", "Mango", "Grapes", "Orange"])
print(prices)

Apple     120
Banana     40
Mango      80
Grapes     60
Orange     50
dtype: int64

In [ ]:
# Create a DataFrame with 4 employees having columns: employee_id, name, department, salary. Use any sample data you like.
employees = pd.DataFrame({
    "Employee_id": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Department": ["HR", "IT", "Finance", "Marketing"],
    "Salary": [60000, 75000, 55000, 80000]
})

print(employees)

   Employee_id     Name Department  Salary
0            1    Alice         HR   60000
1            2      Bob         IT   75000
2            3  Charlie    Finance   55000
3            4    David  Marketing   80000

In [ ]:
# From the DataFrame you created in Exercise 3, extract just the name column. What type is it?
print(type(employees["Name"]))

<class 'pandas.core.series.Series'>

In [ ]:
df = pd.DataFrame({
    "order_id": [1, 2, 3],
    "product": ["Laptop", "Mouse", "Keyboard"],
    "amount": [50000, 500, 1500]
})
print(df)

   order_id   product  amount
0         1    Laptop   50000
1         2     Mouse     500
2         3  Keyboard    1500

In [ ]:
data = [
    {"name": "Alice", "age": 28, "city": "Mumbai"},
    {"name": "Bob", "age": 35, "city": "Delhi"},
    {"name": "Charlie", "age": 22, "city": "Pune"}
]
df = pd.DataFrame(data)
print(df)

      name  age    city
0    Alice   28  Mumbai
1      Bob   35   Delhi
2  Charlie   22    Pune

In [ ]:
data = [
    [1, "Laptop", 50000],
    [2, "Mouse", 500],
    [3, "Keyboard", 1500]
]
df = pd.DataFrame(data, columns=["order_id", "product", "amount"])

In [ ]:
print(df)

   order_id   product  amount
0         1    Laptop   50000
1         2     Mouse     500
2         3  Keyboard    1500

In [ ]:
transactions = [
    {"txn_id": "T001", "customer": "Alice", "amount": 1200.50, "status": "success"},
    {"txn_id": "T002", "customer": "Bob", "amount": 800.00, "status": "failed"},
    {"txn_id": "T003", "customer": "Alice", "amount": 450.75, "status": "success"},
    {"txn_id": "T004", "customer": "Charlie", "amount": 2100.00, "status": "pending"},
]

df = pd.DataFrame(transactions)
print(df)

  txn_id customer   amount   status
0   T001    Alice  1200.50  success
1   T002      Bob   800.00   failed
2   T003    Alice   450.75  success
3   T004  Charlie  2100.00  pending

In [ ]:
# Create a DataFrame of 5 products using a dictionary of lists with columns: product_id, product_name, category, price.
products = pd.DataFrame({
    "product_id": [1, 2, 3, 4, 5],
    "product_name": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headphones"],
    "category": ["Electronics", "Electronics", "Electronics", "Electronics", "Electronics"],
    "price": [800,200,300,1000,400]})

In [ ]:
print(products)

   product_id product_name     category  price
0           1       Laptop  Electronics    800
1           2        Mouse  Electronics    200
2           3     Keyboard  Electronics    300
3           4      Monitor  Electronics   1000
4           5   Headphones  Electronics    400

In [ ]:
data = [
    {"sensor_id": "S1", "temperature": 34.5, "humidity": 60},
    {"sensor_id": "S2", "temperature": 28.1, "humidity": 75},
    {"sensor_id": "S3", "temperature": 31.0, "humidity": 55}
]

df = pd.DataFrame(data)
print(df)

  sensor_id  temperature  humidity
0        S1         34.5        60
1        S2         28.1        75
2        S3         31.0        55

In [ ]:
# Create a DataFrame from a list of lists with columns student_id, name, grade for 4 students.
students = pd.DataFrame([
    ["s1", "Alice", 90],
    ["s2", "Bob", 85],
    ["s3", "Charlie", 78],
    ["s4", "David", 92]
], columns=["student_id", "name", "grade"])

print(students)

  student_id     name  grade
0         s1    Alice     90
1         s2      Bob     85
2         s3  Charlie     78
3         s4    David     92

In [ ]:
# Create an empty DataFrame with columns log_id, timestamp, event, severity. Then print its shape.
empty_df = pd.DataFrame(columns=["log_id", "timestamp", "event", "severity"])
print(empty_df.shape)

(0, 4)

In [ ]:
print(empty_df)

Empty DataFrame
Columns: [log_id, timestamp, event, severity]
Index: []

In [ ]:
df = pd.read_csv("/content/customers.csv")

In [ ]:
# print 10 rows of the data
print(df.head(10))

   customer_id first_name last_name                        email  \
0            1     Ranbir     Sinha            tvyas@example.com
1            2      Qadim    Munshi       shettyveda@example.org
2            3     Mahika     Datta           gmanne@example.net
3            4    Vrishti       Sha       bavachaaya@example.net
4            5      Faras     Loyal  ektapadmanabhan@example.com
5            6   Eiravati     Gupta       aradhana66@example.org
6            7    Krishna     Vohra           veda26@example.com
7            8     Nikita     Ahuja           arya20@example.com
8            9     Pranit      Sane          ikapoor@example.com
9           10     Balvan  Randhawa       vyanjana58@example.com

          phone  gender date_of_birth registration_date         city  \
0    3625670770    Male    2006-11-23        2022-05-24     Kottayam
1    2495821009    Male    1990-11-18        2024-07-09      Silchar
2  918652521286  Female    1997-04-12        2025-03-02         Agra
3  912393804790    Male    1988-08-24        2023-11-04       Guntur
4     472612657    Male    1978-12-08        2025-07-30         Agra
5     136768273    Male    1979-02-09        2025-02-22  Navi Mumbai
6    6233448294    Male    1994-10-14        2021-08-19       Rajkot
7    1510515708    Male    2000-12-05        2025-03-03       Nadiad
8  914708088704  Female    2003-08-31        2023-11-12    Faridabad
9    9214118612    Male    1971-06-25        2025-08-26      Ramgarh

            state country
0  Andhra Pradesh   India
1         Gujarat   India
2          Odisha   India
3    Chhattisgarh   India
4          Sikkim   India
5         Tripura   India
6   Uttar Pradesh   India
7         Tripura   India
8       Karnataka   India
9       Telangana   India

In [ ]:
df = pd.read_json("/content/sample_data/anscombe.json")

In [ ]:
print(df.head(10))

  Series   X      Y
0      I  10   8.04
1      I   8   6.95
2      I  13   7.58
3      I   9   8.81
4      I  11   8.33
5      I  14   9.96
6      I   6   7.24
7      I   4   4.26
8      I  12  10.84
9      I   7   4.81

In [ ]:
import json
json_str = '[{"id": 1, "name": "Alice"}, {"id": 2, "name": "Bob"}]'
df = pd.read_json(json_str)

/tmp/ipykernel_873/1387416273.py:3: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(json_str)

In [ ]:
print(df)

   id   name
0   1  Alice
1   2    Bob

In [ ]:
data = [
    {"id": 1, "name": "Alice", "address": {"city": "Mumbai", "pin": "400001"}},
    {"id": 2, "name": "Bob", "address": {"city": "Delhi", "pin": "110001"}}
]

df = pd.json_normalize(data)
print(df.columns)
# ['id', 'name', 'address.city', 'address.pin']

Index(['id', 'name', 'address.city', 'address.pin'], dtype='object')

In [ ]:
print(df)

   id   name address.city address.pin
0   1  Alice       Mumbai      400001
1   2    Bob        Delhi      110001

In [ ]:
df2 = pd.read_csv("/content/orders.csv")
print(df.head(10))

  customer_id,first_name,last_name,email,phone,gender,date_of_birth,registration_date,city,state,country
0  1,Ranbir,Sinha,tvyas@example.com,3625670770,Ma...
1  2,Qadim,Munshi,shettyveda@example.org,02495821...
2  3,Mahika,Datta,gmanne@example.net,+91865252128...
3  4,Vrishti,Sha,bavachaaya@example.net,+91239380...
4  5,Faras,Loyal,ektapadmanabhan@example.com,0047...
5  6,Eiravati,Gupta,aradhana66@example.org,001367...
6  7,Krishna,Vohra,veda26@example.com,06233448294...
7  8,Nikita,Ahuja,arya20@example.com,1510515708,M...
8  9,Pranit,Sane,ikapoor@example.com,+91470808870...
9  10,Balvan,Randhawa,vyanjana58@example.com,0921...

In [ ]:
# Read a CSV of orders
orders = pd.read_csv("/content/orders.csv", parse_dates=["order_date"])

# Quick look
print(orders.shape)        # how many rows & columns

(10000, 8)

In [ ]:
print(orders.dtypes)        # check data types

order_id                    int64
customer_id                 int64
order_date         datetime64[ns]
order_status               object
total_amount                int64
shipping_amount             int64
tax_amount                float64
discount_amount             int64
dtype: object

In [ ]:

# Save cleaned data as Parquet for downstream pipeline
orders.to_parquet("orders_clean.parquet", index=False)

In [ ]:
df1 = pd.read_parquet("/content/orders_clean.parquet")
print(df1.head())

   order_id  customer_id          order_date order_status  total_amount  \
0         1          765 2025-08-13 04:27:28      Shipped          4161
1         2          721 2024-08-21 06:22:34      Shipped         46098
2         3          713 2025-12-25 08:06:36   Processing          2226
3         4          109 2025-10-09 09:29:28    Delivered         46467
4         5          892 2024-11-14 19:50:11      Shipped         39423

   shipping_amount  tax_amount  discount_amount
0              110      748.98              985
1              243     8297.64              750
2              240      400.68               55
3              294     8364.06              857
4               65     7096.14              150

In [ ]:
print(df.head())

  customer_id,first_name,last_name,email,phone,gender,date_of_birth,registration_date,city,state,country
0  1,Ranbir,Sinha,tvyas@example.com,3625670770,Ma...
1  2,Qadim,Munshi,shettyveda@example.org,02495821...
2  3,Mahika,Datta,gmanne@example.net,+91865252128...
3  4,Vrishti,Sha,bavachaaya@example.net,+91239380...
4  5,Faras,Loyal,ektapadmanabhan@example.com,0047...

In [ ]:
 # Write code to read a CSV file called customers.csv where the separator is | (pipe) instead of comma.
 df = pd.read_csv("/content/customers.csv", sep='|')
 print(df.head())

  customer_id,first_name,last_name,email,phone,gender,date_of_birth,registration_date,city,state,country
0  1,Ranbir,Sinha,tvyas@example.com,3625670770,Ma...
1  2,Qadim,Munshi,shettyveda@example.org,02495821...
2  3,Mahika,Datta,gmanne@example.net,+91865252128...
3  4,Vrishti,Sha,bavachaaya@example.net,+91239380...
4  5,Faras,Loyal,ektapadmanabhan@example.com,0047...

In [ ]:
data = [
    {"order_id": 1, "customer": {"name": "Alice", "email": "alice@mail.com"}, "total": 1500},
    {"order_id": 2, "customer": {"name": "Bob", "email": "bob@mail.com"}, "total": 2300}
]
students = pd.json_normalize(data)
print(students)

   order_id  total customer.name  customer.email
0         1   1500         Alice  alice@mail.com
1         2   2300           Bob    bob@mail.com

In [ ]:
students.to_json("students.json", orient="records")

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5],
    "customer": ["Alice", "Bob", "Alice", None, "Charlie"],
    "amount": [1200.5, 800.0, 450.75, 2100.0, None],
    "status": ["success", "failed", "success", "pending", "success"],
    "order_date": ["2024-01-15", "2024-01-16", "2024-01-16", "2024-01-17", "2024-01-17"]
})

In [ ]:
df.head()      # first 5 rows (default)
df.head(3)     # first 3 rows
df.tail(2)     # last 2 rows

   order_id customer   amount   status  order_date
0         1    Alice  1200.50  success  2024-01-15
1         2      Bob   800.00   failed  2024-01-16
2         3    Alice   450.75  success  2024-01-16

In [ ]:
df.shape       # (5, 5) → 5 rows, 5 columns

(5, 5)

In [ ]:
df.dtypes

order_id        int64
customer       object
amount        float64
status         object
order_date     object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5 non-null      int64
 1   customer    4 non-null      object
 2   amount      4 non-null      float64
 3   status      5 non-null      object
 4   order_date  5 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [ ]:
df.describe()             # only numeric columns

       order_id       amount
count  5.000000     4.000000
mean   3.000000  1137.812500
std    1.581139   710.846132
min    1.000000   450.750000
25%    2.000000   712.687500
50%    3.000000  1000.250000
75%    4.000000  1425.375000
max    5.000000  2100.000000

In [ ]:
df.describe(include="all")  # include string columns too

        order_id customer       amount   status  order_date
count   5.000000        4     4.000000        5           5
unique       NaN        3          NaN        3           3
top          NaN    Alice          NaN  success  2024-01-16
freq         NaN        2          NaN        3           2
mean    3.000000      NaN  1137.812500      NaN         NaN
std     1.581139      NaN   710.846132      NaN         NaN
min     1.000000      NaN   450.750000      NaN         NaN
25%     2.000000      NaN   712.687500      NaN         NaN
50%     3.000000      NaN  1000.250000      NaN         NaN
75%     4.000000      NaN  1425.375000      NaN         NaN
max     5.000000      NaN  2100.000000      NaN         NaN

In [ ]:
df.columns    # Index(['order_id', 'customer', 'amount', 'status', 'order_date'], dtype='object')

Index(['order_id', 'customer', 'amount', 'status', 'order_date'], dtype='object')

In [ ]:
df.index      # RangeIndex(start=0, stop=5, step=1)

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.isna()

   order_id  customer  amount  status  order_date
0     False     False   False   False       False
1     False     False   False   False       False
2     False     False   False   False       False
3     False      True   False   False       False
4     False     False    True   False       False

In [ ]:
df.isnull().sum()

order_id      0
customer      1
amount        1
status        0
order_date    0
dtype: int64

In [ ]:
print("Shape:", df.shape)
print("\nDtypes:\n", df.dtypes)
print("\nNull counts:\n", df.isnull().sum())
print("\nSample:\n", df.head())
df.info()

Shape: (5, 5)

Dtypes:
 order_id        int64
customer       object
amount        float64
status         object
order_date     object
dtype: object

Null counts:
 order_id      0
customer      1
amount        1
status        0
order_date    0
dtype: int64

Sample:
    order_id customer   amount   status  order_date
0         1    Alice  1200.50  success  2024-01-15
1         2      Bob   800.00   failed  2024-01-16
2         3    Alice   450.75  success  2024-01-16
3         4     None  2100.00  pending  2024-01-17
4         5  Charlie      NaN  success  2024-01-17
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5 non-null      int64
 1   customer    4 non-null      object
 2   amount      4 non-null      float64
 3   status      5 non-null      object
 4   order_date  5 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [ ]:
df = pd.DataFrame({
    "order_id": [1, 2, 3, 4],
    "customer": ["Alice", "Bob", "Charlie", "Diana"],
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "amount": [50000, 500, 1500, 22000],
    "status": ["delivered", "shipped", "delivered", "pending"]
})

In [ ]:
df[["customer", "amount"]]

  customer  amount
0    Alice   50000
1      Bob     500
2  Charlie    1500
3    Diana   22000

In [ ]:
df[2:]

   order_id customer   product  amount     status
2         3  Charlie  Keyboard    1500  delivered
3         4    Diana   Monitor   22000    pending

In [ ]:
summary = df[["customer", "amount"]]
print(summary)

  customer  amount
0    Alice   50000
1      Bob     500
2  Charlie    1500
3    Diana   22000

In [ ]:
df["amount"] > 2000

0     True
1    False
2    False
3     True
Name: amount, dtype: bool

In [ ]:
df[df["amount"] > 2000]

   order_id customer  product  amount     status
0         1    Alice   Laptop   50000  delivered
3         4    Diana  Monitor   22000    pending

In [ ]:
# Equal to
df[df["customer"] == "Alice"]

   order_id customer product  amount     status
0         1    Alice  Laptop   50000  delivered

In [ ]:
# Not equal to
df[df["status"] != "cancelled"]

   order_id customer   product  amount     status
0         1    Alice    Laptop   50000  delivered
1         2      Bob     Mouse     500    shipped
2         3  Charlie  Keyboard    1500  delivered
3         4    Diana   Monitor   22000    pending

In [ ]:
# Greater than / Less than
df[df["amount"] >= 1000]

   order_id customer   product  amount     status
0         1    Alice    Laptop   50000  delivered
2         3  Charlie  Keyboard    1500  delivered
3         4    Diana   Monitor   22000    pending

In [ ]:
# String contains
df[df["customer"].str.contains("li")]

   order_id customer   product  amount     status
0         1    Alice    Laptop   50000  delivered
2         3  Charlie  Keyboard    1500  delivered

In [ ]:
# Value in a list (like SQL IN)
df[df["status"].isin(["delivered", "shipped"])]

   order_id customer   product  amount     status
0         1    Alice    Laptop   50000  delivered
1         2      Bob     Mouse     500    shipped
2         3  Charlie  Keyboard    1500  delivered

In [ ]:
# AND — both conditions must be true
df[(df["customer"] == "Alice") & (df["amount"] > 1000)]

   order_id customer product  amount     status
0         1    Alice  Laptop   50000  delivered

In [ ]:
# OR — either condition can be true
df[(df["status"] == "delivered") | (df["status"] == "shipped")]

   order_id customer   product  amount     status
0         1    Alice    Laptop   50000  delivered
1         2      Bob     Mouse     500    shipped
2         3  Charlie  Keyboard    1500  delivered

In [ ]:
# NOT — negate with ~
df[~(df["status"] == "cancelled")]

   order_id customer   product  amount     status
0         1    Alice    Laptop   50000  delivered
1         2      Bob     Mouse     500    shipped
2         3  Charlie  Keyboard    1500  delivered
3         4    Diana   Monitor   22000    pending

In [ ]:
# Find all failed transactions above ₹5000 (needs investigation)
suspicious = df[(df["status"] == "failed") & (df["amount"] > 5000)]
print(suspicious)

Empty DataFrame
Columns: [order_id, customer, product, amount, status]
Index: []

In [ ]:
# Find orders with missing customer info
missing_customer = df[df["customer"].isnull()]
print(missing_customer)

Empty DataFrame
Columns: [order_id, customer, product, amount, status]
Index: []

In [ ]:
# Keep only completed orders for the report
completed = df[df["status"].isin(["delivered", "shipped"])]
print(completed)

   order_id customer   product  amount     status
0         1    Alice    Laptop   50000  delivered
1         2      Bob     Mouse     500    shipped
2         3  Charlie  Keyboard    1500  delivered

In [ ]:
df = pd.DataFrame({
    "emp_id": [101, 102, 103, 104, 105, 106],
    "name": ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank"],
    "dept": ["Engineering", "Sales", "Engineering", "HR", "Sales", "Engineering"],
    "salary": [75000, 55000, 80000, 48000, 52000, 90000],
    "experience_yrs": [5, 3, 7, 2, 4, 10]
})
print(df)

   emp_id     name         dept  salary  experience_yrs
0     101    Alice  Engineering   75000               5
1     102      Bob        Sales   55000               3
2     103  Charlie  Engineering   80000               7
3     104    Diana           HR   48000               2
4     105      Eve        Sales   52000               4
5     106    Frank  Engineering   90000              10

In [ ]:
#Exercise 1: Filter employees with salary greater than 60000.
high_salary = df[df["salary"] > 60000]
print(high_salary)

   emp_id     name         dept  salary  experience_yrs
0     101    Alice  Engineering   75000               5
2     103  Charlie  Engineering   80000               7
5     106    Frank  Engineering   90000              10

In [ ]:
#Exercise 2: Filter employees in the "Engineering" department.
engineering_dept = df[df["dept"] == "Engineering"]
print(engineering_dept)

   emp_id     name         dept  salary  experience_yrs
0     101    Alice  Engineering   75000               5
2     103  Charlie  Engineering   80000               7
5     106    Frank  Engineering   90000              10

In [ ]:
#Exercise 3: Filter employees who are in "Sales" AND have more than 3 years experience.
sales_and_exp = df[(df["dept"] == "Sales") & (df["experience_yrs"] > 3)]
print(sales_and_exp)

   emp_id name   dept  salary  experience_yrs
4     105  Eve  Sales   52000               4

In [ ]:
#Exercise 4: Filter employees who earn less than 50000 OR have less than 3 years experience.
low_salary_or_exp = df[(df["salary"] < 50000) | (df["experience_yrs"] < 3)]
print(low_salary_or_exp)

   emp_id   name dept  salary  experience_yrs
3     104  Diana   HR   48000               2

In [ ]:
#Exercise 5: Filter employees whose name contains the letter "a" (case-insensitive).
a_name = df[df["name"].str.contains("a", case=False)]
print(a_name)

   emp_id     name         dept  salary  experience_yrs
0     101    Alice  Engineering   75000               5
2     103  Charlie  Engineering   80000               7
3     104    Diana           HR   48000               2
5     106    Frank  Engineering   90000              10

In [ ]:
#Exercise 6: Filter employees in departments "Engineering" or "HR" using isin().
engineering_or_hr = df[df["dept"].isin(["Engineering", "HR"])]
print(engineering_or_hr)

   emp_id     name         dept  salary  experience_yrs
0     101    Alice  Engineering   75000               5
2     103  Charlie  Engineering   80000               7
3     104    Diana           HR   48000               2
5     106    Frank  Engineering   90000              10

In [ ]:
df = pd.DataFrame({
    "product": ["Keyboard", "Laptop", "Mouse", "Monitor", "Headset"],
    "category": ["Accessories", "Electronics", "Accessories", "Electronics", "Accessories"],
    "price": [1500, 50000, 500, 22000, 2000],
    "stock": [200, 30, 500, 45, 150]
})
print(df)

    product     category  price  stock
0  Keyboard  Accessories   1500    200
1    Laptop  Electronics  50000     30
2     Mouse  Accessories    500    500
3   Monitor  Electronics  22000     45
4   Headset  Accessories   2000    150

In [ ]:
df.sort_values("price", ascending=False)

    product     category  price  stock
1    Laptop  Electronics  50000     30
3   Monitor  Electronics  22000     45
4   Headset  Accessories   2000    150
0  Keyboard  Accessories   1500    200
2     Mouse  Accessories    500    500

In [ ]:
df.sort_values("stock", ascending=False)

    product     category  price  stock
2     Mouse  Accessories    500    500
0  Keyboard  Accessories   1500    200
4   Headset  Accessories   2000    150
3   Monitor  Electronics  22000     45
1    Laptop  Electronics  50000     30

In [ ]:
# Sort by category A-Z, then price highest first within each category
df.sort_values(["category", "price"], ascending=[True, False])

    product     category  price  stock
4   Headset  Accessories   2000    150
0  Keyboard  Accessories   1500    200
2     Mouse  Accessories    500    500
1    Laptop  Electronics  50000     30
3   Monitor  Electronics  22000     45

In [ ]:
df.sort_index()

    product     category  price  stock
0  Keyboard  Accessories   1500    200
1    Laptop  Electronics  50000     30
2     Mouse  Accessories    500    500
3   Monitor  Electronics  22000     45
4   Headset  Accessories   2000    150

In [ ]:
df.sort_index(ascending=False)

    product     category  price  stock
4   Headset  Accessories   2000    150
3   Monitor  Electronics  22000     45
2     Mouse  Accessories    500    500
1    Laptop  Electronics  50000     30
0  Keyboard  Accessories   1500    200

In [ ]:
print(df)

    product     category  price  stock
0  Keyboard  Accessories   1500    200
1    Laptop  Electronics  50000     30
2     Mouse  Accessories    500    500
3   Monitor  Electronics  22000     45
4   Headset  Accessories   2000    150

In [ ]:
df.sort_values("price", na_position="first")   # NaNs at top

    product     category  price  stock
2     Mouse  Accessories    500    500
0  Keyboard  Accessories   1500    200
4   Headset  Accessories   2000    150
3   Monitor  Electronics  22000     45
1    Laptop  Electronics  50000     30

In [ ]:
df.sort_values("price", na_position="last")    # NaNs at bottom (default)

    product     category  price  stock
2     Mouse  Accessories    500    500
0  Keyboard  Accessories   1500    200
4   Headset  Accessories   2000    150
3   Monitor  Electronics  22000     45
1    Laptop  Electronics  50000     30

In [ ]:
df = pd.DataFrame({
    "txn_id": ["T001", "T002", "T003", "T004", "T005", "T006"],
    "customer": ["Alice", "Bob", "Charlie", "Alice", "Eve", "Bob"],
    "amount": [1200, 350, 4500, 800, 150, 3200],
    "date": ["2024-01-15", "2024-01-14", "2024-01-16", "2024-01-15", "2024-01-13", "2024-01-16"]
})
# Sort orders by amount descending, take top 10
top_orders = df.sort_values("amount", ascending=False)
print(top_orders.head(10))

  txn_id customer  amount        date
2   T003  Charlie    4500  2024-01-16
5   T006      Bob    3200  2024-01-16
0   T001    Alice    1200  2024-01-15
3   T004    Alice     800  2024-01-15
1   T002      Bob     350  2024-01-14
4   T005      Eve     150  2024-01-13

In [ ]:
# Sort by date then amount for a clean report
report = df.sort_values(["date", "amount"], ascending=[True, False])
print(report)

  txn_id customer  amount        date
4   T005      Eve     150  2024-01-13
1   T002      Bob     350  2024-01-14
0   T001    Alice    1200  2024-01-15
3   T004    Alice     800  2024-01-15
2   T003  Charlie    4500  2024-01-16
5   T006      Bob    3200  2024-01-16

In [ ]:
# Exercise 4 — Sort by date
df.sort_values("date")
# It sorts alphabetically as STRING, not chronologically!
# "2024-01-13" < "2024-01-14" works here by luck.
# But for proper date sorting, convert to datetime first:
df["date"] = pd.to_datetime(df["date"])
df.sort_values("date")

  txn_id customer  amount       date
4   T005      Eve     150 2024-01-13
1   T002      Bob     350 2024-01-14
0   T001    Alice    1200 2024-01-15
3   T004    Alice     800 2024-01-15
2   T003  Charlie    4500 2024-01-16
5   T006      Bob    3200 2024-01-16

In [1]:
import pandas as pd

df = pd.DataFrame({
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "price": [50000, 500, 1500, 22000],
    "quantity": [2, 10, 5, 3]
})

In [2]:
df["total"] = df["price"] * df["quantity"]
print(df)

    product  price  quantity   total
0    Laptop  50000         2  100000
1     Mouse    500        10    5000
2  Keyboard   1500         5    7500
3   Monitor  22000         3   66000

In [ ]:
df["currency"] = "INR"

In [ ]:
df["is_expensive"] = df["price"] > 5000

In [ ]:
print(df)

    product  price  quantity   total currency  is_expensive
0    Laptop  50000         2  100000      INR          True
1     Mouse    500        10    5000      INR         False
2  Keyboard   1500         5    7500      INR         False
3   Monitor  22000         3   66000      INR          True

In [ ]:
df["price"] = df["price"] * 1.1   # 10% price increase

In [ ]:
df.loc[df["product"] == "Mouse", "price"] = 450

In [ ]:
print(df)

    product    price  quantity   total currency  is_expensive
0    Laptop  55000.0         2  100000      INR          True
1     Mouse    450.0        10    5000      INR         False
2  Keyboard   1650.0         5    7500      INR         False
3   Monitor  24200.0         3   66000      INR          True

In [ ]:
# Rename specific columns
df = df.rename(columns={"price": "unit_price", "quantity": "qty"})

In [ ]:
print(df)

    product  unit_price  qty   total currency  is_expensive
0    Laptop     55000.0    2  100000      INR          True
1     Mouse       450.0   10    5000      INR         False
2  Keyboard      1650.0    5    7500      INR         False
3   Monitor     24200.0    3   66000      INR          True

In [ ]:
# Rename ALL columns at once
df.columns = ["prod", "unit_price", "qty", "total", "curr", "expensive"]
print(df)

       prod  unit_price  qty   total curr  expensive
0    Laptop     55000.0    2  100000  INR       True
1     Mouse       450.0   10    5000  INR      False
2  Keyboard      1650.0    5    7500  INR      False
3   Monitor     24200.0    3   66000  INR       True

In [ ]:
# Drop multiple columns
df = df.drop(columns=["curr", "expensive"])
print(df)

       prod  unit_price  qty   total
0    Laptop     55000.0    2  100000
1     Mouse       450.0   10    5000
2  Keyboard      1650.0    5    7500
3   Monitor     24200.0    3   66000

In [ ]:
# Rename columns
df.columns = ["product", "price", "quantity", "total"]

# Reordering columns
df = df[["product", "quantity", "price", "total"]]
print(df)

    product  quantity  price   total
0    Laptop   55000.0      2  100000
1     Mouse     450.0     10    5000
2  Keyboard    1650.0      5    7500
3   Monitor   24200.0      3   66000

In [ ]:
# Raw order data
orders = pd.DataFrame({
    "order_id": [1, 2, 3],
    "item": ["Laptop", "Mouse", "Monitor"],
    "unit_price": [50000, 500, 22000],
    "qty": [2, 10, 3],
    "tax_pct": [18, 18, 18]
})
print(orders)

   order_id     item  unit_price  qty  tax_pct
0         1   Laptop       50000    2       18
1         2    Mouse         500   10       18
2         3  Monitor       22000    3       18

In [ ]:

# Add calculated columns
orders["subtotal"] = orders["unit_price"] * orders["qty"]
orders["tax_amount"] = orders["subtotal"] * orders["tax_pct"] / 100
orders["total"] = orders["subtotal"] + orders["tax_amount"]

# Drop the intermediate column
orders = orders.drop(columns=["tax_pct"])

# Rename for downstream system
orders = orders.rename(columns={"item": "product_name", "qty": "quantity"})

print(orders)

   order_id product_name  unit_price  quantity  subtotal  tax_amount     total
0         1       Laptop       50000         2    100000     18000.0  118000.0
1         2        Mouse         500        10      5000       900.0    5900.0
2         3      Monitor       22000         3     66000     11880.0   77880.0

In [ ]:
df = pd.DataFrame({
    "emp_id": [101, 102, 103, 104],
    "name": ["Alice", "Bob", "Charlie", "Diana"],
    "base_salary": [75000, 55000, 80000, 60000],
    "bonus_pct": [10, 15, 12, 8]
})
print(df)

   emp_id     name  base_salary  bonus_pct
0     101    Alice        75000         10
1     102      Bob        55000         15
2     103  Charlie        80000         12
3     104    Diana        60000          8

In [ ]:
# Exercise 1: Add a new column bonus_amount = base_salary * bonus_pct / 100.

df["bonus_amount"] = df["base_salary"] * df["bonus_pct"] / 100

In [ ]:
#Exercise 2: Add a column total_salary = base_salary + bonus_amount.

df["total_salary"] = df["base_salary"] + df["bonus_amount"]

In [ ]:
#Exercise 3: Add a column level with value "Senior" for salary > 70000, else "Junior". (Hint: look up np.where)

import numpy as np
df["level"] = np.where(df["base_salary"] > 70000, "Senior", "Junior")

print(df)

   emp_id     name  base_salary  bonus_pct  bonus_amount  total_salary   level
0     101    Alice        75000         10        7500.0       82500.0  Senior
1     102      Bob        55000         15        8250.0       63250.0  Junior
2     103  Charlie        80000         12        9600.0       89600.0  Senior
3     104    Diana        60000          8        4800.0       64800.0  Junior

In [ ]:
#Exercise 4: Rename base_salary to base_pay and bonus_pct to bonus_percentage.

df = df.rename(columns={"base_salary": "base_pay", "bonus_pct": "bonus_percentage"})
print(df)

   emp_id     name  base_pay  bonus_percentage  bonus_amount  total_salary  \
0     101    Alice     75000                10        7500.0       82500.0
1     102      Bob     55000                15        8250.0       63250.0
2     103  Charlie     80000                12        9600.0       89600.0
3     104    Diana     60000                 8        4800.0       64800.0

    level
0  Senior
1  Junior
2  Senior
3  Junior

In [ ]:
#Exercise 5: Drop the bonus_pct (or bonus_percentage) column.

df = df.drop(columns=["bonus_percentage"])
print(df)

   emp_id     name  base_pay  bonus_amount  total_salary   level
0     101    Alice     75000        7500.0       82500.0  Senior
1     102      Bob     55000        8250.0       63250.0  Junior
2     103  Charlie     80000        9600.0       89600.0  Senior
3     104    Diana     60000        4800.0       64800.0  Junior

In [ ]:
#Exercise 6: Reorder columns as: emp_id, name, level, base_salary, bonus_amount, total_salary.

df = df[["emp_id", "name", "level", "base_pay", "bonus_amount", "total_salary"]]

print(df)

   emp_id     name   level  base_pay  bonus_amount  total_salary
0     101    Alice  Senior     75000        7500.0       82500.0
1     102      Bob  Junior     55000        8250.0       63250.0
2     103  Charlie  Senior     80000        9600.0       89600.0
3     104    Diana  Junior     60000        4800.0       64800.0

### Data Aggregation

Aggregation is the process of combining multiple rows into a single summary row based on one or more grouping keys. Common aggregation functions include `sum()`, `mean()`, `min()`, `max()`, and `count()`.

In [ ]:
# Group by department and calculate the average base pay
avg_salary_by_dept = df.groupby('level')['base_pay'].mean().reset_index()
print(avg_salary_by_dept)

    level  base_pay
0  Junior   57500.0
1  Senior   77500.0

In [ ]:
# Group by level and calculate multiple aggregations
salary_stats_by_level = df.groupby('level').agg(
    min_base_pay=('base_pay', 'min'),
    max_base_pay=('base_pay', 'max'),
    avg_base_pay=('base_pay', 'mean'),
    count_employees=('emp_id', 'count'),
    avg_total_salary=('total_salary', 'mean')
).reset_index()
print(salary_stats_by_level)

    level  min_base_pay  max_base_pay  avg_base_pay  count_employees  \
0  Junior         55000         60000       57500.0                2
1  Senior         75000         80000       77500.0                2

   avg_total_salary
0           64025.0
1           86050.0